# -*- coding: utf-8 -*-
"""pyhton class 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10C-lqADCjrJg_UgthN7jefQVxXqOxz0u
"""

print("Gopal")

print("5" + "5")

print(5 +int("5"))

print(5 + "5")

print(str(5) + "5")

print()

print("hi" * 3)

print("Welcome to python Programming")
print("Let's start our coding journey")

print('let's start our coding journey')

print("*" * 10)

print("My Profile")


print("*" * 10)


print("Name: Harsh Gopal")


print("Role: Student")


print("Interest: Data Science AI & ML")

print("*" * 1)
print("*" * 2)
print("*" * 3)
print("*" * 4)
print("*" * 5)

print("*" * 10 + "INVOICE" + "*" * 10)
print("Product: Laptop")
print("Price: 100000000000")
print("gst: 10000000")
print("Total: 10000000000000000000")
print("*" * 20)

print("**********INVOICE**********","Product: Laptop","Price: 100000000000","Gst: 1000000",sep="\n")